/* eslint-disable @typescript-eslint/camelcase */
import axios from 'axios';

export class Posts {
  backendUrl: string;
  token: string;

  constructor(backendUrl: string, token?: string) {
    this.backendUrl = backendUrl;
    this.token = token;
  }

  setToken(token?: string): object {
    this.token = token;
    return this;
  }

  async getPosts(id?: string): Promise<unknown> {
    // try {
    // const url = id
    //     ? `${this.backendUrl}/api/v4/posts/${id}`
    //     : `${this.backendUrl}/api/v4/posts/`;
    //   const config = this.token
    //     ? {
    //         headers: { Authorization: `Bearer ${this.token}` },
    //       }
    //     : {};
    // await axios.get(url, config);
    try {
      const url = id
        ? `${this.backendUrl}/api/v3/posts/${id}`
        : `${this.backendUrl}/api/v3/posts/`;
      const config = this.token
        ? {
            headers: { Authorization: `Bearer ${this.token}` },
          }
        : {};
      const result = await axios.get(url, config);
      let post = result.data;
      post.form = {
        id: 63,
        name: 'safasfsdsdgsdg',
        parent_id: null,
        description: 'ENglish description',
        type: 'report',
        disabled: false,
        require_approval: true,
        everyone_can_create: false,
        color: '#A51A1A',
        hide_author: false,
        hide_time: 0,
        hide_location: 0,
        targeted_survey: 0,
        translations: {
          sw: { name: 'Survey-name in swahili', description: 'Swahili desc' },
          'hy-AM': { name: 'sdgsdgsdg' },
        },
        tasks: [
          {
            id: 70,
            form_id: 63,
            label: 'Post',
            priority: 0,
            required: 0,
            type: 'post',
            description: null,
            show_when_published: 1,
            task_is_internal_only: 0,
            fields: [
              {
                id: 182,
                key: '225f7884-019b-461f-ba8f-1e2ea0ed9c14',
                label: 'Title',
                instructions: null,
                input: 'text',
                type: 'title',
                required: 1,
                default: null,
                priority: 1,
                options: null,
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Title in Swahili', instructions: '' },
                },
              },
              {
                id: 183,
                key: '6967f800-a864-4e78-84a9-9db264b40599',
                label: 'Description',
                instructions: null,
                input: 'text',
                type: 'description',
                required: 1,
                default: null,
                priority: 2,
                options: [],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Description in Swahili', instructions: '' },
                },
              },
              {
                id: 217,
                key: 'e3fbfe3b-e13a-4adc-83da-d4273f71826d',
                label: 'cat',
                instructions: '',
                input: 'tags',
                type: 'tags',
                required: 0,
                default: null,
                priority: 3,
                options: [19, 20, 17, 13, 22, 21],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Category field-name', instructions: '' },
                },
              },
              {
                id: 218,
                key: '73574021-483b-48e8-9646-457a9cf4fb7f',
                label: 'Short text',
                instructions: 'Hello',
                input: 'text',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 4,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 219,
                key: '560b1b7e-6fa9-4433-ab32-369716289648',
                label: 'Date',
                instructions: '',
                input: 'date',
                type: 'datetime',
                required: 0,
                default: null,
                priority: 5,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 220,
                key: '824ccb51-eddb-4cb3-a834-6686c99b99f9',
                label: 'Date and time',
                instructions: '',
                input: 'datetime',
                type: 'datetime',
                required: 0,
                default: null,
                priority: 6,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Date and time in Swahili', instructions: '' },
                },
              },
              {
                id: 221,
                key: 'd06e2e88-8e43-406c-9144-480fae9b8f5a',
                label: 'Select',
                instructions: '',
                input: 'select',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 7,
                options: ['Option 1', 'Option 2'],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 222,
                key: '9e04edc4-49be-4581-a8b0-a95578b9a60d',
                label: 'Number',
                instructions: '',
                input: 'number',
                type: 'decimal',
                required: 0,
                default: null,
                priority: 8,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 223,
                key: 'd4d0872b-8458-44b8-9fe7-e479f91d6334',
                label: 'Number int',
                instructions: '',
                input: 'number',
                type: 'int',
                required: 0,
                default: null,
                priority: 9,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 224,
                key: '90511e81-f247-4ca0-8b5a-f93a084d30cb',
                label: 'Location',
                instructions: '',
                input: 'location',
                type: 'point',
                required: 0,
                default: null,
                priority: 10,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 225,
                key: 'db9c8208-854f-47af-8224-14a2a983fc40',
                label: 'Image',
                instructions: '',
                input: 'upload',
                type: 'media',
                required: 0,
                default: null,
                priority: 11,
                options: [],
                cardinality: 1,
                config: { hasCaption: true },
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 226,
                key: 'cc3d2b04-2565-4607-bfd8-cfff7704bf76',
                label: 'Video',
                instructions: '',
                input: 'video',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 12,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 227,
                key: '7fbe2205-aab7-4a1d-bd0c-526f586c4693',
                label: 'Radio',
                instructions: '',
                input: 'radio',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 13,
                options: ['Option 1', 'Option 2'],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 228,
                key: '1932672f-70b4-42cc-b212-da8e7724e4ef',
                label: 'Checkbox',
                instructions: '',
                input: 'checkbox',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 14,
                options: ['Option 1', 'Option 2'],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 231,
                key: '555fb666-a7a6-44b3-b48d-ecf260f5503a',
                label: 'Markdown',
                instructions: '',
                input: 'markdown',
                type: 'markdown',
                required: 0,
                default: null,
                priority: 15,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 83,
            form_id: 63,
            label: 'New task',
            priority: 1,
            required: 1,
            type: 'task',
            description: 'Task',
            show_when_published: 0,
            task_is_internal_only: 1,
            fields: [
              {
                id: 229,
                key: '61ef5dc4-a94f-46c3-829f-0d9ac6451b1c',
                label: 'Long text',
                instructions: '',
                input: 'textarea',
                type: 'text',
                required: 0,
                default: null,
                priority: 0,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 83,
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 84,
            form_id: 63,
            label: 'Third task',
            priority: 2,
            required: 0,
            type: 'task',
            description: null,
            show_when_published: 0,
            task_is_internal_only: 1,
            fields: [
              {
                id: 230,
                key: '6d9b8120-f29f-48d6-b66d-f5bf31af4832',
                label: 'Related post',
                instructions: '',
                input: 'relation',
                type: 'relation',
                required: 0,
                default: null,
                priority: 0,
                options: [],
                cardinality: 1,
                config: { input: { form: [63, 64] } },
                response_private: 0,
                form_stage_id: 84,
                translations: [],
              },
            ],
            translations: [],
          },
        ],
        can_create: ['admin'],
        enabled_languages: { default: 'myv', available: ['sw', 'hy-AM'] },
      };
      post.description = post.content;
       post.post_content = [
          {
            id: 70,
            form_id: 63,
            label: 'Post',
            priority: 0,
            required: 0,
            type: 'post',
            description: null,
            show_when_published: 1,
            task_is_internal_only: 0,
            fields: [
              {
                id: 182,
                key: '225f7884-019b-461f-ba8f-1e2ea0ed9c14',
                label: 'Title',
                instructions: null,
                input: 'text',
                type: 'title',
                required: 1,
                default: null,
                priority: 1,
                options: null,
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Title in Swahili', instructions: '' },
                },
                value: 'Title',
              },
              {
                id: 183,
                key: '6967f800-a864-4e78-84a9-9db264b40599',
                label: 'Description',
                instructions: null,
                input: 'text',
                type: 'description',
                required: 1,
                default: null,
                priority: 2,
                options: [],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Description in Swahili', instructions: '' },
                },
                value: 'Description',
              },
              {
                id: 217,
                key: 'e3fbfe3b-e13a-4adc-83da-d4273f71826d',
                label: 'cat',
                instructions: '',
                input: 'tags',
                type: 'tags',
                required: 0,
                default: null,
                priority: 3,
                options: [19, 20, 17, 13, 22, 21],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Category field-name', instructions: '' },
                },
                value: ['17', '19', '20', '22'],
              },
              {
                id: 218,
                key: '73574021-483b-48e8-9646-457a9cf4fb7f',
                label: 'Short text',
                instructions: 'Hello',
                input: 'text',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 4,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
                value: 'Short text',
              },
              {
                id: 219,
                key: '560b1b7e-6fa9-4433-ab32-369716289648',
                label: 'Date',
                instructions: '',
                input: 'date',
                type: 'datetime',
                required: 0,
                default: null,
                priority: 5,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 220,
                key: '824ccb51-eddb-4cb3-a834-6686c99b99f9',
                label: 'Date and time',
                instructions: '',
                input: 'datetime',
                type: 'datetime',
                required: 0,
                default: null,
                priority: 6,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: {
                  sw: { label: 'Date and time in Swahili', instructions: '' },
                },
              },
              {
                id: 221,
                key: 'd06e2e88-8e43-406c-9144-480fae9b8f5a',
                label: 'Select',
                instructions: '',
                input: 'select',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 7,
                options: ['Option 1', 'Option 2'],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 222,
                key: '9e04edc4-49be-4581-a8b0-a95578b9a60d',
                label: 'Number',
                instructions: '',
                input: 'number',
                type: 'decimal',
                required: 0,
                default: null,
                priority: 8,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 223,
                key: 'd4d0872b-8458-44b8-9fe7-e479f91d6334',
                label: 'Number int',
                instructions: '',
                input: 'number',
                type: 'int',
                required: 0,
                default: null,
                priority: 9,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 224,
                key: '90511e81-f247-4ca0-8b5a-f93a084d30cb',
                label: 'Location',
                instructions: '',
                input: 'location',
                type: 'point',
                required: 0,
                default: null,
                priority: 10,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 225,
                key: 'db9c8208-854f-47af-8224-14a2a983fc40',
                label: 'Image',
                instructions: '',
                input: 'upload',
                type: 'media',
                required: 0,
                default: null,
                priority: 11,
                options: [],
                cardinality: 1,
                config: { hasCaption: true },
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 226,
                key: 'cc3d2b04-2565-4607-bfd8-cfff7704bf76',
                label: 'Video',
                instructions: '',
                input: 'video',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 12,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 227,
                key: '7fbe2205-aab7-4a1d-bd0c-526f586c4693',
                label: 'Radio',
                instructions: '',
                input: 'radio',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 13,
                options: ['Option 1', 'Option 2'],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 228,
                key: '1932672f-70b4-42cc-b212-da8e7724e4ef',
                label: 'Checkbox',
                instructions: '',
                input: 'checkbox',
                type: 'varchar',
                required: 0,
                default: null,
                priority: 14,
                options: ['Option 1', 'Option 2'],
                cardinality: 0,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
              {
                id: 231,
                key: '555fb666-a7a6-44b3-b48d-ecf260f5503a',
                label: 'Markdown',
                instructions: '',
                input: 'markdown',
                type: 'markdown',
                required: 0,
                default: null,
                priority: 15,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 70,
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 83,
            form_id: 63,
            label: 'New task',
            priority: 1,
            required: 1,
            type: 'task',
            description: 'Task',
            show_when_published: 0,
            task_is_internal_only: 1,
            fields: [
              {
                id: 229,
                key: '61ef5dc4-a94f-46c3-829f-0d9ac6451b1c',
                label: 'Long text',
                instructions: '',
                input: 'textarea',
                type: 'text',
                required: 0,
                default: null,
                priority: 0,
                options: [],
                cardinality: 1,
                config: [],
                response_private: 0,
                form_stage_id: 83,
                translations: [],
              },
            ],
            translations: [],
          },
          {
            id: 84,
            form_id: 63,
            label: 'Third task',
            priority: 2,
            required: 0,
            type: 'task',
            description: null,
            show_when_published: 0,
            task_is_internal_only: 1,
            fields: [
              {
                id: 230,
                key: '6d9b8120-f29f-48d6-b66d-f5bf31af4832',
                label: 'Related post',
                instructions: '',
                input: 'relation',
                type: 'relation',
                required: 0,
                default: null,
                priority: 0,
                options: [],
                cardinality: 1,
                config: { input: { form: [63, 64] } },
                response_private: 0,
                form_stage_id: 84,
                translations: [],
              },
            ],
            translations: [],
          },
        ];
        return post;
       
  } catch (err) {
    console.log(err);
    return err;
  }
    // return response.data.result || response.data.results;
    //  catch (err) {
    //   return err;
    // }
  }

  async savePost(post: { id?: string }): Promise<unknown> {
    // const method = post.id ? 'put' : 'post';
    // const url = post.id
    //   ? `${this.backendUrl}/api/v4/posts/${post.id}`
    //   : `${this.backendUrl}/api/v4/posts/`;
    // const res = await axios({
    //   method: method,
    //   url: url,
    //   headers: {
    //     Authorization: `Bearer ${this.token}`,
    //   },
    //   data: post,
    // });
    console.log(post);
    return post;
  }
}

const post = new Posts('http://192.168.33.110', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjliOWQyZjQxNWM4MmUxMDcxYWMzZWQwOTg1MzI1OWZjMzljZjZjZTc0Mjc5OWM2ZjM4NGRhYWI2NDE2NGRlY2M3MjM4OGM5MDM3MTRkMGYyIn0.eyJhdWQiOiJ1c2hhaGlkaXVpIiwianRpIjoiOWI5ZDJmNDE1YzgyZTEwNzFhYzNlZDA5ODUzMjU5ZmMzOWNmNmNlNzQyNzk5YzZmMzg0ZGFhYjY0MTY0ZGVjYzcyMzg4YzkwMzcxNGQwZjIiLCJpYXQiOjE1OTE1OTQwODksIm5iZiI6MTU5MTU5NDA4OSwiZXhwIjoxNTkxNjgwNDg5LCJzdWIiOiIxIiwic2NvcGVzIjpbIioiXX0.OAtM2mgQmVoKK-hWFc3dLZzYLjELLF61Uy6fWrd8DvA4Imy_Okc5R3VsVRLpIvkahzoMiNRzMO8HRLexFV8agmOdUP_mhL6ugt7it033uvXh2SmftdAKI6Ml7QwsP8jhaAYpZfCle30s-l0AgELHWeoBL5_994U_LLYg0kFBwWpywAMkM-A8s8Mnk53alk9EPGiCHLBdF3CcK7uiZtGTUpQvt6JvCRhsMKA5NF0cDpN0E-fiXF27FbQx_cGgraXmllLJkWsSCL1SdhsBsRoBS50rasjWEkPxIe5ZTJtYEffmWNUUnIqnKDK62EU5XQuqGqEA4Jx2vwPnusnx4hzRlvjuNsOfY40RteeqF0vZNqUDbc6voX0Hk6EEHI3NGQmvafcGY8dIAlkn_kuU4WF0wLiaNNJ5JB6nqB2dxoG_6As2_49ZJjtTQEsU8pwSr06ot9rso8POXaIr8Z6ch2xYEQMUTxiImUCxIGcmKwvtM9C_jlKGSbiV0QZLwjfe8PJOFkqyLnjd6eRu7yiuAPYdklX5JVsVOgAo0flsm04KbvAuF1BsnSpSSO8gtl7z0jAhDhiOfDTbVG_YOkevpRaP-RExCX-iDidKrufREBlyu2xTXupM_WQxsTyWgK3VOWIZqhHl0oCl4_THrjXsUELypgYIlkP9kgQYg_6x5iYwvOI');
post.getPosts('63').then(res => {
  console.log('hello');
  return res;
});
